### ISSUE TITLE
Regular Expression Denial of Service

### ISSUE THREAD

**Issue by amitguptagwl** [Leanty/tree-gateway#102]
As mentioned on [nodesecurity.io](https://nodesecurity.io/check/tree-gateway), can you please confirm if we have Regular Expression Denial of Service vulnerability?

Same is reported by [snyk.io](https://snyk.io/test/npm/tree-gateway?severity=high&severity=medium&severity=low) as well.

**Comment by thiagobustamante** [comment]
Hi, 

Thank you for report it. 

The dependency 'serve-favicon' is not being used by tree-gateway. So it is not causing any vulnerability. But it should not being declared in our package.json file.

I am removing it right now.

**Comment by amitguptagwl** [comment]
Great!! thanks for your quick assitance. I was just looking for production ready API gateway like getkong. And I found  tree-gateway. But before using it, I wanted to ensure it is covering all security and performance aspects.

Thanks again.
