### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by figueiredoAF** [Leanty/tree-gateway#130]
Hello,

I'm having an authentication problem using the ADMIN REST API.  The user was created with the following command:

`treeGatewayConfig users add -l sampleuserlogin -p sampleuserpassword -n sampleusername -r admin config`

I received the message "User created", and I have seen the user was really inserted in my database instance.

However, I get a "user not found" response when I try to get the access token for the user, doing a POST in /users/authentication with the login and password as parameters.

Does anyone know what's going on?

Best regards,
Alex F. Figueiredo.

**Comment by thiagobustamante** [comment]
I could not reproduce it. I created the user using your command and then authenticate without any problem.

Maybe there is a problem in the way you are passing those parameters... Did you tested through the swagger ui interface (http://localhost:8001/api-docs)?
