### ISSUE TITLE
I think it needs another dashboard for the apis that added by user

### ISSUE THREAD

**Issue by yuzhigang33** [Leanty/tree-gateway#16]
@thiagobustamante  have plan to add a dashboard (like the current admin api-doc) for the user apis ? So that user can manage api in pages.

**Comment by thiagobustamante** [comment]
Yes. We are already implementing it. We are working to build a platform that allow remote administration for the gateway. It will work following a 'micro gateway' architecture and support  APIs management, statistics monitoring, automated deploys (integrating clouds providers like amazon, google etc) and even services composition or APIs creation from the scratch.

This platform is under development, but will not be open source. That's how we plan to support our business. But the gateway itself is completely free and the code will remains open here in github.  

However, I think that It is possible to use some ready dashboard, like [Grafana](https://grafana.com/) to create a simpler dashboard which may be able to meet your demand. 
It would be great to have a plugin to connect to Grafana. We would appreciate any help with this implementation.

**Comment by yuzhigang33** [comment]
Thanks, and when could i use your commercial  product？

**Comment by thiagobustamante** [comment]
We expect to have a first release by September.

**Comment by thiagobustamante** [comment]
Our community edition is ready and [running](http://dashboard.leanty.com).

You need to install the [tree-gateway-agent](https://www.npmjs.com/package/tree-gateway-agent) anywhere in your infra.

```
npm install -g tree-gateway-agent
```

And then, just run the agent:

```
treeGatewayAgent
```
