### ISSUE TITLE
Allow compression to be disabled

### ISSUE THREAD

**Issue by fabsrc** [Leanty/tree-gateway#97]
At the moment the compression module is used by default:
https://github.com/Leanty/tree-gateway/blob/d6b3de2309df92016f1acf57ad55448097ed5e20/src/gateway.ts#L423

This is fine of course, but when a reverse proxy like nginx or Apache is used the compression should be implemented on that level (see http://expressjs.com/en/advanced/best-practice-performance.html#use-gzip-compression). Therefore it would be nice if there was a config which allows you to disable the compression in the node application.

**Comment by thiagobustamante** [comment]
Yes, I agree. I will address this to next release
